--FAÇA.. ENQUANTO (FOR VERDADE) X ENQUANTO CONDIÇÃO ESTÁ INICIO... FAÇA ?
DECLARE
BEGIN
LOOP -- INICIANDO O LAÇO
IF C1%FOUND THEN
MSG := MSG||RC1.EMPNO||' - ';
ELSE
EXIT;
END IF;
END LOOP; -- TENHO QUE FINALIZAR O COMANDO COM END LOOP (OBRIGATÓRIO).
DBMS_OUTPUT.PUT_LINE(MSG);
END;